// ============================================================
// SafeTrack AI — Hardcoded Dummy Data
// ============================================================

export const dashboardStats = {
  totalWorkers: 150,
  activeCameras: 12,
  violationsToday: 5,
  safetyScore: 87,
  activeAlerts: 3,
  zonesMonitored: 8,
};

export const violationsLog = [
  {
    id: "VIO-001",
    type: "Helmet",
    description: "Pekerja tanpa helm terdeteksi",
    timestamp: "2026-05-31 08:15:22",
    cameraLocation: "Zona A - Produksi",
    camera: "CAM-03",
    status: "Open",
    severity: "High",
    worker: "Ahmad Fauzi",
  },
  {
    id: "VIO-002",
    type: "Red Zone Intrusion",
    description: "Akses tidak sah ke zona berbahaya",
    timestamp: "2026-05-31 09:02:47",
    cameraLocation: "Zona B - Gudang",
    camera: "CAM-07",
    status: "Open",
    severity: "Critical",
    worker: "Budi Santoso",
  },
  {
    id: "VIO-003",
    type: "Vest",
    description: "Safety vest tidak digunakan",
    timestamp: "2026-05-31 09:45:10",
    cameraLocation: "Zona C - Loading Dock",
    camera: "CAM-01",
    status: "Resolved",
    severity: "Medium",
    worker: "Citra Dewi",
  },
  {
    id: "VIO-004",
    type: "Hairnet",
    description: "Hairnet tidak terdeteksi di area makanan",
    timestamp: "2026-05-31 10:12:33",
    cameraLocation: "Zona D - Packaging",
    camera: "CAM-09",
    status: "Open",
    severity: "Medium",
    worker: "Dian Permata",
  },
  {
    id: "VIO-005",
    type: "Helmet",
    description: "Helm tidak dipakai saat mengoperasikan forklift",
    timestamp: "2026-05-31 11:30:05",
    cameraLocation: "Zona A - Produksi",
    camera: "CAM-04",
    status: "Resolved",
    severity: "High",
    worker: "Eko Prasetyo",
  },
  {
    id: "VIO-006",
    type: "Red Zone Intrusion",
    description: "Pekerja memasuki zona merah tanpa izin",
    timestamp: "2026-05-31 12:08:19",
    cameraLocation: "Zona B - Gudang",
    camera: "CAM-07",
    status: "Open",
    severity: "Critical",
    worker: "Fajar Nugroho",
  },
  {
    id: "VIO-007",
    type: "Vest",
    description: "Rompi keselamatan tidak dikenakan",
    timestamp: "2026-05-31 13:22:41",
    cameraLocation: "Zona C - Loading Dock",
    camera: "CAM-02",
    status: "Resolved",
    severity: "Medium",
    worker: "Gita Savitri",
  },
  {
    id: "VIO-008",
    type: "Helmet",
    description: "Pekerja melepas helm di area konstruksi",
    timestamp: "2026-05-31 14:05:58",
    cameraLocation: "Zona A - Produksi",
    camera: "CAM-05",
    status: "Open",
    severity: "High",
    worker: "Hendra Wijaya",
  },
  {
    id: "VIO-009",
    type: "Hairnet",
    description: "Tidak memakai hairnet di ruang steril",
    timestamp: "2026-05-31 14:55:12",
    cameraLocation: "Zona D - Packaging",
    camera: "CAM-10",
    status: "Resolved",
    severity: "Low",
    worker: "Indah Lestari",
  },
  {
    id: "VIO-010",
    type: "Red Zone Intrusion",
    description: "Intrusi terdeteksi di zona terbatas",
    timestamp: "2026-05-31 15:30:00",
    cameraLocation: "Zona B - Gudang",
    camera: "CAM-08",
    status: "Open",
    severity: "Critical",
    worker: "Joko Susilo",
  },
];

export const cameraFeeds = [
  { id: "CAM-01", location: "Zona C - Loading Dock", status: "Online", zone: "C", image: "/cam-loading.png" },
  { id: "CAM-02", location: "Zona C - Loading Dock", status: "Online", zone: "C", image: "/cam-loading.png" },
  { id: "CAM-03", location: "Zona A - Produksi", status: "Online", zone: "A", image: "/cam-production.png" },
  { id: "CAM-04", location: "Zona A - Produksi", status: "Online", zone: "A", image: "/cam-production.png" },
  { id: "CAM-05", location: "Zona A - Produksi", status: "Offline", zone: "A", image: "/cam-production.png" },
  { id: "CAM-06", location: "Zona B - Gudang", status: "Online", zone: "B", image: "/cam-warehouse.png" },
  { id: "CAM-07", location: "Zona B - Gudang", status: "Online", zone: "B", image: "/cam-warehouse.png" },
  { id: "CAM-08", location: "Zona B - Gudang", status: "Online", zone: "B", image: "/cam-warehouse.png" },
  { id: "CAM-09", location: "Zona D - Packaging", status: "Online", zone: "D", image: "/cam-packaging.png" },
  { id: "CAM-10", location: "Zona D - Packaging", status: "Online", zone: "D", image: "/cam-packaging.png" },
  { id: "CAM-11", location: "Zona A - Produksi", status: "Online", zone: "A", image: "/cam-production.png" },
  { id: "CAM-12", location: "Zona D - Packaging", status: "Offline", zone: "D", image: "/cam-packaging.png" },
];

export const violationTrend = [
  { time: "06:00", violations: 0 },
  { time: "07:00", violations: 1 },
  { time: "08:00", violations: 2 },
  { time: "09:00", violations: 3 },
  { time: "10:00", violations: 1 },
  { time: "11:00", violations: 2 },
  { time: "12:00", violations: 1 },
  { time: "13:00", violations: 3 },
  { time: "14:00", violations: 4 },
  { time: "15:00", violations: 2 },
  { time: "16:00", violations: 1 },
  { time: "17:00", violations: 0 },
];

export const violationsByType = [
  { name: "Helmet", value: 35, color: "#f97316" },
  { name: "Vest", value: 25, color: "#3b82f6" },
  { name: "Red Zone", value: 25, color: "#ef4444" },
  { name: "Hairnet", value: 15, color: "#a855f7" },
];

export const recentActivity = [
  { id: 1, message: "AI mendeteksi pekerja tanpa helm di Zona A", time: "2 menit lalu", type: "warning" },
  { id: 2, message: "Intrusi zona merah terdeteksi di Zona B", time: "15 menit lalu", type: "critical" },
  { id: 3, message: "Pelanggaran VIO-005 telah diselesaikan", time: "30 menit lalu", type: "success" },
  { id: 4, message: "Kamera CAM-05 offline — periksa koneksi", time: "1 jam lalu", type: "info" },
  { id: 5, message: "Safety vest violation di Loading Dock", time: "1.5 jam lalu", type: "warning" },
];
